apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgCLPETHfabfqAVMW5o3pyIMD50HT+IWDHc28VhjBZlHRBXGk4I0jzpxEuHFcnNkMWYzXx/y25VFkAE3A/C2La5YsxdIJQTZYFGwqaTKRe5p2jvsTc1jDYTpON58Bl9aBJP9kNIT56nxGmTbwZSi+mnqYyavq6RnB/kaSiECcUrh1/kQbIw66WQmslgGW4suJLTNNfEnYGkV/XAVqyC33IzQb8Q59fmpJEOr51a0/C5Oi0974avf/o9oTGnwQM0bX5ugGML3mEYCZrgL1c3BSyx19/1rtuWbaakjGokXl6r4FwNjdsZNejvsHCChpGzfOS6es3TXutXBUvc+wBPIEeyYnfid5loP6W2nUbkfkEXSUI5xve0z6t8GZNKsEOAQ/2GinVvSKwqBQrJk7kja5CtN1ePdXNWDeU7xkFtOQIWwtfQfbACpw1GHP7DUBpZcRmiQG7/nyCtiLHTpNuu4Zwf9NC9hmgspHf5VFfWiAy/F/Ifi+SBxrGu/XvsVcjYDS47qPAHiRpQc3R63/fJ3km2BGgwNbUbE0H4PEPAk+Na+rfRUM5k7svaDLr5eHNYLef3lkdA0IfOjwRstct/wDeZtJUPsrAQp+zWtsF8C3U/qVoKs6Uj9rV+sfmLLPQf0ERnmUyYO2UvGMyYCzDf1y4bSs0NBiqYD3tZwmkY4XZqC9m2DO2MqgVBRlR6Bw2YggKad3OasSatSd0fUSc2aPZ6uT7S7/+d4Kmh9K9MQfnlaQMwzQWNRNdhW
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

